# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-23 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydict',
            options={'verbose_name': '\u57ce\u5e02', 'verbose_name_plural': '\u57ce\u5e02'},
        ),
    ]
